version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: quiz-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: quiz_server_db
      MYSQL_USER: quizuser
      MYSQL_PASSWORD: quizpass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - quiz-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: quiz-phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - quiz-network

volumes:
  mysql_data:

networks:
  quiz-network:
    driver: bridge
